### ISSUE TITLE
Raw Code Node : from a file

### ISSUE THREAD

**Issue by MaraScott** [filliptm/ComfyUI_Fill-Nodes#8]
Hi, would it be possible to add a feature to load a file from it's abs path ?

**Comment by Amorano** [comment]
> Hi, would it be possible to add a feature to load a file from it's abs path ?

Should it load the code into the window (before Queue like with images)? or should it just have a "file name" input and simply load the file at execute?

**Comment by MaraScott** [comment]
Only filename should be fine. However a preview of the first lines or the name of the main class / function might help to identify the code in the wf.
The main idea would be to have access to all the python libraries available when coding a node in comfyui like import comfyui for instance and to get access to relative path relative to the file loaded.

**Comment by Amorano** [comment]
> Only filename should be fine. However a preview of the first lines or the name of the main class / function might help to identify the code in the wf. The main idea would be to have access to all the python libraries available when coding a node in comfyui like import comfyui for instance and to get access to relative path relative to the file loaded.

You would have access to the venv that ComfyUI builds -- in order to add more libs you'd need to hack it in, runtime. 

I did an update to allow for Code File loads (relative to the comfy install and absolute path). Seems ok?

![image](https://github.com/filliptm/ComfyUI_Fill-Nodes/assets/225178/b01e8b94-f62b-4dba-af42-0f8a80b7a20a)

**Comment by MaraScott** [comment]
Super, looks awesome.
I ll check that soon.
